### ISSUE TITLE
thoughts on adding this to ember-composable-helpers?

### ISSUE THREAD

**Issue by SirZach** [cibernox/ember-assign-helper#1]
Thanks for putting this together! https://github.com/DockYard/ember-composable-helpers seems like an addon that's really building out useful helpers like this one. Any thoughts on adding this to that library for consolidation?

**Comment by cibernox** [comment]
I needed this now, but if they want this helper I'll be happy to deprecate it and point people to ember-composable-helpers.

**Comment by miguelcobain** [comment]
Until we have proper tree shaking, I think including ember-composable-helpers isn't a viable alternative if you just want an assign helper.

**Comment by cibernox** [comment]
iirc, ember-composable-helpers has a way of whitelisting helpers, but I don't know if addons can access that API and extend the whitelist provided by the app.

**Comment by SirZach** [comment]
Again just a thought. No need for immediate action. Thanks again for getting it out there
